"""empty message

Revision ID: 29f72c7eec46
Revises: 
Create Date: 2024-12-05 16:33:18.267461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f72c7eec46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=200), nullable=True),
    sa.Column('startdate', sa.Date(), nullable=True),
    sa.Column('starttime', sa.Time(), nullable=True),
    sa.Column('enddate', sa.Date(), nullable=True),
    sa.Column('endtime', sa.Time(), nullable=True),
    sa.Column('place', sa.String(length=200), nullable=True),
    sa.Column('notice', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('memo', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('users')
    # ### end Alembic commands ###
